#server:
#  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: filmbuff-discovery.herokuapp.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://filmbuff-discovery.herokuapp.com/eureka
  